jobmanager.web.port: 8081
jobmanager.rpc.port: 6123
jobmanager.heap.mb: 28048

parallelization.degree.default: 4

high-availability: zookeeper
high-availability.zookeeper.quorum: <zks>
high-availability.zookeeper.path.root: <zkpath>
high-availability.zookeeper.storageDir: s3://<dir>
high-availability.jobmanager.port: 8082
high-availability.zookeeper.path.namespace: <namespace>

fs.hdfs.hadoopconf: config/hadoop/

state.backend: filesystem
state.checkpoints.dir: s3://<dir>
state.backend.fs.checkpointdir: s3://<dir>





